### ISSUE TITLE
support Yarn links

### ISSUE THREAD

**Issue by johntellsall** [vasilevich/sync-yarnlock-into-packagejson#2]
example dependency:

`"@tuitionio/tio-backend-services": "link:../tio-backend-services",
`
I expect it to be passed through unchanged, but at the moment the version is set to zero:

`"@tuitionio/tio-backend-services": "0.0.0",`

**Comment by johntellsall** [comment]
Btw THANKS so much for writing this utility! It's super easy and obvious to use :)

**Comment by vasilevich** [comment]
Hi! thank you for giving me a chance!
I will take a look and take care of it shortly.

**Comment by vasilevich** [comment]
Hi there, I have implemented the fix you requested, 
please note I have moved the package into a different name to make it work better:
https://www.npmjs.com/package/syncyarnlock
just remove the previous package and install this one
`npm install -g syncyarnlock`
and then to run it with the link feature please try
syncyarnlock -l

if it doesn't work, please attach your sample yarn.lock file (or make an example with this link feature) so I can test it, I did not test because I don't know this link: feature.

please re-open issuse if you have a problem.

best of luck!
